name: rofl
description: A new ROFL project.

dependencies:
  flutter:
    sdk: flutter
  flushbar: ^1.5.0
  grouped_buttons: ^1.0.3
  gradient_app_bar: ^0.0.1
  fab_circular_menu: ^1.0.0
  flutter_speed_dial: ^1.2.5
  flappy_search_bar: 1.4.1
  flutter_spinkit: "^2.1.0"
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  flutter_datetime_picker:
    git:
      url: https://github.com/derohimat/flutter_datetime_picker.git



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: 0.16.1
  rflutter_alert: ^1.0.2
  cloud_firestore:  ^0.13.4+2
  firebase_database: 3.1.6
  universal_html: 1.2.3
  dio: 1.0.0
  # new



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    - assets/backg.jpg
    - assets/option2.png
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.io/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.io/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.io/custom-fonts/#from-packages